# Generated by Django 6.0 on 2026-01-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_initial'),
        ('housing', '0002_alter_room_options_hostel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='allocated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='bed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation', to='housing.bed'),
        ),
    ]
