# Generated by Django 6.0 on 2026-01-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_alter_room_options_hostel_address_and_more'),
        ('operations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='feedback',
            field=models.TextField(blank=True, help_text='Response or feedback from maintenance staff'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='housing.room'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='title',
            field=models.CharField(default='Maintenance Issue', max_length=200),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='category',
            field=models.CharField(choices=[('WIFI', 'WiFi'), ('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('FURNITURE', 'Furniture'), ('CLEANING', 'Cleaning'), ('AC_FAN', 'AC/Fan'), ('DOOR_LOCK', 'Door/Lock'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('VIEWED', 'Viewed'), ('IN_PROGRESS', 'In Progress'), ('WAITING_PARTS', 'Waiting for Parts'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
