# Generated by Django 6.0 on 2026-01-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['hostel', 'room_number']},
        ),
        migrations.AddField(
            model_name='hostel',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='allocated_batches',
            field=models.CharField(blank=True, help_text="Comma-separated batch years, e.g., '21,22,23'", max_length=50),
        ),
        migrations.AddField(
            model_name='hostel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hostel', 'room_number')},
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='housing.room')),
            ],
            options={
                'ordering': ['room', 'bed_number'],
                'unique_together': {('room', 'bed_number')},
            },
        ),
    ]
