# Generated by Django 6.0 on 2026-01-26 00:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_requests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outpass',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='swaprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='outpass',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outpass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outpass',
            name='destination',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='outpass',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='outpass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='outpass',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='outpass',
            name='warden_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='student_b_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='student_b_enrollment',
            field=models.CharField(default='', help_text='Enrollment number of student to swap with', max_length=50),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='student_b_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='warden_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='outpass',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VIEWED', 'Viewed'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.CharField(choices=[('PENDING_B', 'Waiting for Partner Approval'), ('PENDING_WARDEN', 'Waiting for Warden Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_B', max_length=20),
        ),
        migrations.CreateModel(
            name='HostelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('semester', models.CharField(default='Spring 2026', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VIEWED', 'Viewed'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why do you need hostel accommodation?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('hostel_request', 'Hostel Request'), ('swap_request', 'Swap Request'), ('outpass', 'Outpass'), ('ticket', 'Maintenance Ticket')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Status histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
