# Generated by Django 6.0 on 2026-02-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_requests', '0003_alter_outpass_options_alter_swaprequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (required when rejecting)'),
        ),
        migrations.AlterField(
            model_name='hostelrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
