# Generated by Django 6.0 on 2026-02-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_requests', '0004_hostel_request_status_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelrequest',
            name='rejection_reason',
        ),
        migrations.AlterField(
            model_name='hostelrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VIEWED', 'Viewed'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
