# Generated by Django 6.0 on 2026-02-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_requests', '0005_remove_hostelrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text="Warden's reason for rejection (required if rejected)"),
        ),
        migrations.AlterField(
            model_name='hostelrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
