# Generated by Django 6.0 on 2026-02-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_requests', '0006_hostelrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelrequest',
            name='semester',
            field=models.CharField(default='2025/2026 - Semester 1', max_length=50),
        ),
    ]
