# Generated by Django 6.0 on 2025-12-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_enrollment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
